spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/library?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: ${MYSQL_STRATEGY:update} #Change this to create when you run application first time to automatically create tables

server:
  port: ${SPRING_PORT:8080}